### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by Ap3teus** [Ap3teus/craftjs-javascript#10]
1. start the server
2. reload CraftJS (`/js refresh()`)
3. a player joins the server
->

```
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: Exception in thread "ForkJoinPool.commonPool-worker-5" java.lang.IllegalStateException: The Context is already closed.
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:126)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosed(PolyglotContextImpl.java:741)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:474)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1603)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:87)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:505)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:482)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:448)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:432)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget$OptimizedCallProfiled.call(OptimizedCallTarget.java:1425)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropValue.canInvoke(PolyglotValue.java:2820)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.graalvm.sdk/org.graalvm.polyglot.Value.canInvokeMember(Value.java:525)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.oracle.truffle.js.runtime.java.adapter.JavaAdapterServices.hasMethod(JavaAdapterServices.java:105)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.bukkit.command.Command$$JSJavaAdapter.testPermissionSilent(Unknown Source)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:48)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:20)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.minecraft.server.v1_16_R1.CommandDispatcher.a(CommandDispatcher.java:300)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.minecraft.server.v1_16_R1.CommandDispatcher.sendAsync(CommandDispatcher.java:264)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.minecraft.server.v1_16_R1.CommandDispatcher.lambda$a$4(CommandDispatcher.java:247)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[00:26:00] [ForkJoinPool.commonPool-worker-5/WARN]: Caused by: Attached Guest Language Frames (1)
```

**Comment by Ap3teus** [comment]
Might be fixed now
